version: '2.1'
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    environment:
      PYTHONPATH: /bmiProject/BMIfinder
      DJANGO_SETTINGS_MODULE: BMIfinder.settings
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest -v -s
            #python manage.py test
      - name: Run tests and collect coverage
        run: |
          pytest --cov=app tests/
          coverage xml --omit="*/venv/*"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
      # - run: pytest --cov=myapp tests/
      # - codecov/upload:
      #     token: "${{ env.CODECOV_TOKEN }}"

workflows:
  build-and-test:
    jobs:
      - build
