version: '2.1'
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    environment:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      PYTHONPATH: /bmiProject/BMIfinder
      DJANGO_SETTINGS_MODULE: BMIfinder.settings
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pip install pytest
            pip install pytest-cov
            pytest -v -s
      - run: pytest --cov=bmiProject/bmiCalc/tests.py
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  build-and-test:
    jobs:
      - build
