version: '2.1'
orbs:
  codecov: codecov/codecov@3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest
            #python manage.py test
      - codecov/upload

workflows:
  build-and-test:
    jobs:
      - build
