version: '2.1'

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test

workflows:
  build-and-test:
    jobs:
      - build
